[package]
name = "mimalloc-rs"
version = "0.1.0"
authors = ["Marcus Klaas de Vries <mail@marcusklaas.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7"
